### ISSUE TITLE
Springboot run with EnkaNetworkAPI

### ISSUE THREAD

**Issue by pmh615279552** [kazuryyx/EnkaNetworkAPI#1]
When I try to automatically assemble the EnkaNetworkAPI in Spring, this error occurs
![image](https://github.com/kazuryyx/EnkaNetworkAPI/assets/34742901/0ff01f13-dde4-465e-97a4-30ef1b76517e)

**Comment by kazuryyx** [comment]
Could you check if this is resolved in 4.4 version? 
Edit: I believe 4.3 solved this when the repository changed branch and I had to accordingly

**Comment by pmh615279552** [comment]
thanks，the problem has been resolved

**Comment by kazuryyx** [comment]
Very nice, for the next time adding the repository use the enka-docs page, it has more code examples and always will be updated rather than the github one
